import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import {normalize} from '../stylesheets/StyleFont';
import Colors from '../constants/Colors';

const StylesHomeScreen = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    backgroundColor: Colors.WhiteColor,
  },
  noDataAvailable: {
    color: Colors.PrimaryColor,
    fontSize: normalize(18),
    margin: hp('10%'),
    alignItems: 'center',
    textAlign: 'center',
  },
  viewRvStyle: {
    paddingBottom: hp('8%'),
    flex: 1,
    alignContent: 'center',
    alignSelf: 'center',
    width: wp('100%'),
  },
  noDataStyle: {
    height: hp('80%'),
    width: wp('100%'),
    alignContent: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
  },
  fabStyle: {
    borderWidth: 0,
    borderColor: 'rgba(0,0,0,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    // width: wp('8%'),
    // height: wp('8%'),
    // backgroundColor: Colors.BlueColor,
    // borderRadius: 100,
    alignContent: 'center',
    marginLeft: wp('3%'),
  },
  IconContianer: {
    flexDirection: 'row',
    marginLeft: wp('0.5%'),
    padding: wp('2%'),
  },
  containerFabStyle: {
    borderWidth: 0,
    borderColor: 'rgba(0,0,0,0.2)',
    alignItems: 'center',
    //justifyContent: 'center',
    width: wp('100%'),
    position: 'absolute',
    bottom: 0,
    height: wp('13%'),
    backgroundColor: '#ededed',
    flexDirection: 'row',
  },
  fabStyleText: {
    color: Colors.WhiteColor,
    fontSize: normalize(20),
    alignSelf: 'center',
    textAlign: 'center',
    alignItems: 'center',
  },
  newReminderTextStyle: {
    color: Colors.BlueColor,
    fontSize: normalize(13),
    fontFamily: 'OpenSans-Medium',
    alignSelf: 'center',
    textAlign: 'center',
    marginLeft: wp('2%'),
  },
  itemContainer: {
    borderBottomWidth: 1,
    borderBottomColor: '#ededed',
    flexDirection: 'row',
    marginBottom: hp('0.5%'),
    alignContent: 'center',
    justifyContent: 'center',
    height: hp('10%'),
  },
  item: {
    color: Colors.LightBlueColor,
    fontSize: normalize(15),
    flex: 4,
    padding: hp('2%'),
    alignSelf: 'center',
  },
  deleteItem: {
    flex: 0.5,
    padding: hp('2.5%'),
    color: '#a3a3a3',
    fontWeight: 'bold',
    marginVertical: hp('0.3%'),
    //backgroundColor: '#ededed',
    alignItems: 'center',
    textAlign: 'center',
  },
  loaderViewStyle: {
    position: 'absolute',
    justifyContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
    elevation: 10,
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 10,
  },
});

export {StylesHomeScreen};
